import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  Activity,
  LogOut,
  Pill,
  Clock,
  TrendingUp,
  AlertCircle,
  X,
  Printer,
  ChevronRight,
  ArrowLeft,
  Share2,
  Loader,
  History,
  Calendar,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import Footer from "../components/Footer";
import Logo from "../components/Logo";
import api from "../utils/api";

function TreatmentRecommendations({ onLogout, currentUser }) {
  const navigate = useNavigate();

  const [selectedTreatment, setSelectedTreatment] = useState(null);

  // History state 
  const [treatmentHistory, setTreatmentHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [expandedId, setExpandedId] = useState(null); 


  useEffect(() => {
    const fetchHistory = async () => {
      try {
        setLoading(true);
        const res = await api.get("/ml/history/treatment");
        setTreatmentHistory(res.data.treatments || []);
      } catch (err) {
        console.error("Failed to fetch treatment history:", err);
        setError("Could not load your treatment history. Please try again.");
      } finally {
        setLoading(false);
      }
    };
    fetchHistory();
  }, []);

  const handleLogout = () => {
    onLogout();
    navigate("/");
  };

  const formatDate = (dateStr) => {
    const d = new Date(dateStr);
    return d.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });
  };

  
  const normalizeTreatment = (record) => {
    const td = record.treatmentData || {};
    const primary = td.primary || td;

    const recommendations = primary.recommendations?.map?.((r, i) => ({
      type: r.type || `Step ${i + 1}`,
      description: r.description || r,
    })) || [];

    return {
      id: record._id,
      condition: record.condition || primary.condition || "Unknown",
      severity: primary.severity || "Low",
      date: formatDate(record.updatedAt || record.createdAt),
      doctor: "AI Health Assistant",
      duration: primary.duration || "As directed",
      followUp: primary.followUp || "Consult your doctor if symptoms persist.",
      notes: primary.notes || "",
      warnings: primary.warnings || [],
      recommendations,
    };
  };

  const severityConfig = {
    Low:    { badge: "badge-success" },
    Medium: { badge: "badge-warning" },
    High:   { badge: "badge-danger"  },
  };

  const RecIcon = ({ type }) => {
    if (type?.toLowerCase().includes("medication") || type?.toLowerCase().includes("drug"))
      return <Pill className="w-5 h-5 text-primary" />;
    if (type?.toLowerCase().includes("rest") || type?.toLowerCase().includes("sleep"))
      return <Clock className="w-5 h-5 text-primary" />;
    return <TrendingUp className="w-5 h-5 text-primary" />;
  };

  const handlePrint = (treatment) => {
    const printWindow = window.open("", "", "height=700,width=900");
    printWindow.document.write(`
      <html>
        <head>
          <title>Treatment Plan — ${treatment.condition}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 30px; color: #1a202c; }
            h1 { font-size: 24px; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }
            h2 { font-size: 18px; margin-top: 20px; }
            .meta { color: #6b7280; font-size: 14px; margin-bottom: 16px; }
            .severity { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 13px; font-weight: bold; background: #fef9c3; color: #92400e; }
            .rec-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }
            .rec-item { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; }
            .rec-type { font-weight: bold; font-size: 14px; }
            .rec-desc { font-size: 13px; color: #6b7280; margin-top: 4px; }
            .warning { background: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: 10px 14px; margin: 6px 0; font-size: 13px; color: #991b1b; }
            .note { background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 12px; font-size: 13px; color: #1e40af; }
            .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 10px; font-size: 12px; color: #9ca3af; }
          </style>
        </head>
        <body>
          <h1>DiagnoSync — Treatment Plan</h1>
          <p class="meta">
            Generated by <strong>${treatment.doctor}</strong> &nbsp;|&nbsp;
            Date: <strong>${treatment.date}</strong> &nbsp;|&nbsp;
            Duration: <strong>${treatment.duration}</strong>
          </p>
          <h2>${treatment.condition} &nbsp;<span class="severity">${treatment.severity} Severity</span></h2>
          <h2>Recommended Treatment Plan</h2>
          <div class="rec-grid">
            ${treatment.recommendations.map(
              (r) => `<div class="rec-item">
              <div class="rec-type">${r.type}</div>
              <div class="rec-desc">${r.description}</div>
            </div>`
            ).join("")}
          </div>
          ${treatment.notes ? `<h2>Clinical Notes</h2><div class="note">${treatment.notes}</div>` : ""}
          ${treatment.warnings?.length > 0 ? `<h2>Warnings</h2>${treatment.warnings.map((w) => `<div class="warning">⚠️ ${w}</div>`).join("")}` : ""}
          <h2>Follow-Up</h2>
          <p>${treatment.followUp}</p>
          <div class="footer">Printed from DiagnoSync Patient Portal — For clinical queries, contact your healthcare provider.</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const normalizedHistory = treatmentHistory.map(normalizeTreatment);

  return (
    <div className="min-h-screen bg-light-gray">
      {/* Navbar */}
      <nav className="glass-panel sticky top-4 z-40 mx-4 sm:mx-6 lg:mx-8 mb-8 border-none shadow-soft backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Logo />
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate("/patient/dashboard")}
                className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-semibold transition-colors flex items-center gap-2"
              >
                <ArrowLeft className="w-4 h-4" />
                <span className="hidden sm:inline">Back to Dashboard</span>
              </button>
              <button
                onClick={handleLogout}
                className="px-4 py-2 bg-red-50 hover:bg-red-100 text-red-600 border border-red-100 rounded-lg text-sm font-semibold transition-colors flex items-center gap-2"
              >
                <LogOut className="w-4 h-4" />
                <span className="hidden sm:inline">Logout</span>
              </button>
            </div>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-[#E5E7EB] mb-2 flex items-center gap-3">
            <Activity className="w-8 h-8 text-primary" />
            Treatment Recommendations
          </h1>
          <p className="text-white">
            Your personalized AI-generated treatment plans based on past symptom analyses.
          </p>
        </div>

        {/* Content*/}
        {loading ? (
          <div className="flex flex-col items-center justify-center py-16">
            <Loader className="w-8 h-8 text-primary animate-spin mb-4" />
            <p className="text-gray-600">Loading your treatment history...</p>
          </div>
        ) : error ? (
          <div className="bg-red-50 p-6 rounded-2xl border border-red-200 text-center mb-8">
            <AlertCircle className="w-8 h-8 text-danger mx-auto mb-2" />
            <p className="text-red-700 font-semibold">{error}</p>
          </div>
        ) : normalizedHistory.length === 0 ? (
          <div className="bg-white rounded-2xl border border-border-gray p-12 text-center shadow-soft">
            <History className="w-12 h-12 text-gray-300 mx-auto mb-4" />
            <h3 className="text-lg font-bold text-dark-gray mb-2">No Treatment History Yet</h3>
            <p className="text-gray-500 mb-6 text-sm">
              Complete a Symptom Checker session to generate your first AI treatment plan.
            </p>
            <button
              onClick={() => navigate("/patient/symptom-checker")}
              className="btn-primary"
            >
              Go to Symptom Checker
            </button>
          </div>
        ) : (
          <div className="space-y-5">
            {normalizedHistory.map((treatment) => (
              <div key={treatment.id} className="bg-white rounded-2xl border border-border-gray shadow-soft overflow-hidden">
                {/* Card header */}
                <div
                  className="flex items-center justify-between p-5 cursor-pointer hover:bg-gray-50 transition-colors"
                  onClick={() => setExpandedId(expandedId === treatment.id ? null : treatment.id)}
                >
                  <div className="flex items-start gap-4">
                    <div className="p-3 bg-blue-50 rounded-xl">
                      <Pill className="w-5 h-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-lg font-bold text-dark-gray">{treatment.condition}</h2>
                      <div className="flex items-center gap-2 text-sm text-gray-500 mt-0.5">
                        <Calendar className="w-3.5 h-3.5" />
                        <span>{treatment.date}</span>
                        <span>·</span>
                        <span>{treatment.doctor}</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className={`${severityConfig[treatment.severity]?.badge || "badge-primary"} hidden sm:inline`}>
                      {treatment.severity}
                    </span>
                    {expandedId === treatment.id
                      ? <ChevronUp className="w-5 h-5 text-gray-400" />
                      : <ChevronDown className="w-5 h-5 text-gray-400" />
                    }
                  </div>
                </div>

                {/* Expandable body */}
                {expandedId === treatment.id && (
                  <div className="border-t border-border-gray px-5 pb-5 pt-4">
                    {/* Recommendations grid */}
                    {treatment.recommendations.length > 0 && (
                      <div className="mb-5">
                        <h3 className="text-base font-bold text-dark-gray mb-3">Recommended Treatment Plan</h3>
                        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
                          {treatment.recommendations.map((rec, i) => (
                            <div
                              key={i}
                              className="p-4 bg-light-gray rounded-xl border border-border-gray"
                            >
                              <div className="flex items-center gap-2 mb-2">
                                <RecIcon type={rec.type} />
                                <h4 className="font-semibold text-dark-gray text-sm">{rec.type}</h4>
                              </div>
                              <p className="text-xs text-gray-600">{rec.description}</p>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Info row */}
                    <div className="flex flex-wrap gap-3 mb-4">
                      <div className="flex-1 min-w-[140px] p-3 bg-light-gray rounded-xl border border-border-gray">
                        <p className="text-xs text-gray-500 font-semibold uppercase tracking-wide mb-1">Duration</p>
                        <p className="font-semibold text-dark-gray text-sm">{treatment.duration}</p>
                      </div>
                      <div className="flex-1 min-w-[140px] p-3 bg-light-gray rounded-xl border border-border-gray">
                        <p className="text-xs text-gray-500 font-semibold uppercase tracking-wide mb-1">Follow-Up</p>
                        <p className="text-sm text-dark-gray">{treatment.followUp}</p>
                      </div>
                    </div>

                    {/* Notes */}
                    {treatment.notes && (
                      <div className="mb-4 p-4 bg-blue-50 rounded-xl border border-blue-200">
                        <p className="text-xs font-semibold text-dark-gray mb-1">Clinical Notes</p>
                        <p className="text-sm text-gray-600">{treatment.notes}</p>
                      </div>
                    )}

                    {/* Warnings */}
                    {treatment.warnings?.length > 0 && (
                      <div className="mb-4 space-y-2">
                        <h4 className="font-bold text-dark-gray text-sm">⚠️ Warnings</h4>
                        {treatment.warnings.map((w, i) => (
                          <div key={i} className="flex gap-2 p-3 bg-red-50 border border-red-100 rounded-xl">
                            <AlertCircle className="w-4 h-4 text-danger flex-shrink-0 mt-0.5" />
                            <p className="text-sm text-red-700">{w}</p>
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Actions */}
                    <div className="flex flex-wrap gap-3 pt-3 border-t border-border-gray">
                      <button
                        onClick={() => setSelectedTreatment(treatment)}
                        className="btn-primary flex items-center gap-2 text-sm"
                      >
                        <ChevronRight className="w-4 h-4" />
                        Full Details
                      </button>
                      <button
                        onClick={() => handlePrint(treatment)}
                        className="btn-secondary flex items-center gap-2 text-sm"
                      >
                        <Printer className="w-4 h-4" />
                        Print Plan
                      </button>
                      <button
                        className="btn-secondary flex items-center gap-2 text-sm opacity-50 cursor-not-allowed"
                        disabled
                        title="Coming soon"
                      >
                        <Share2 className="w-4 h-4" />
                        Share with Doctor
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* CTA */}
        <div className="mt-8 p-6 bg-primary text-white rounded-2xl text-center">
          <h3 className="text-xl font-bold mb-2">Need to Schedule a Consultation?</h3>
          <p className="mb-4 opacity-90">Book an appointment with your doctor for a proper diagnosis</p>
          <button
            onClick={() => navigate("/patient/appointments")}
            className="bg-white text-primary px-6 py-2 rounded-lg font-bold hover:bg-gray-100 transition-colors"
          >
            Book Appointment
          </button>
        </div>

        {/* CTA 2 */}
        <div className="mt-4 p-4 bg-white rounded-2xl border border-border-gray text-center">
          <p className="text-sm text-gray-600 mb-3">Want to run a new symptom check?</p>
          <button
            onClick={() => navigate("/patient/symptom-checker")}
            className="btn-secondary text-sm"
          >
            Start Symptom Checker
          </button>
        </div>
      </div>

      {/*Full Details Modal */}
      {selectedTreatment && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
            <div className="flex items-start justify-between p-6 border-b border-border-gray">
              <div>
                <h2 className="text-2xl font-bold text-dark-gray">{selectedTreatment.condition}</h2>
                <p className="text-sm text-gray-500 mt-1">
                  {selectedTreatment.doctor} &nbsp;·&nbsp; {selectedTreatment.date}
                </p>
              </div>
              <button
                onClick={() => setSelectedTreatment(null)}
                className="text-gray-400 hover:text-gray-600 transition-colors p-1"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="p-6 space-y-6">
              <div className="flex flex-wrap gap-4">
                <div className="flex-1 min-w-[140px] p-4 bg-light-gray rounded-xl border border-border-gray">
                  <p className="text-xs text-gray-500 font-semibold uppercase tracking-wide mb-1">Severity</p>
                  <span className={severityConfig[selectedTreatment.severity]?.badge || "badge-primary"}>
                    {selectedTreatment.severity}
                  </span>
                </div>
                <div className="flex-1 min-w-[140px] p-4 bg-light-gray rounded-xl border border-border-gray">
                  <p className="text-xs text-gray-500 font-semibold uppercase tracking-wide mb-1">Duration</p>
                  <p className="font-semibold text-dark-gray">{selectedTreatment.duration}</p>
                </div>
                <div className="flex-1 min-w-[140px] p-4 bg-light-gray rounded-xl border border-border-gray">
                  <p className="text-xs text-gray-500 font-semibold uppercase tracking-wide mb-1">Follow-Up</p>
                  <p className="text-sm text-dark-gray">{selectedTreatment.followUp}</p>
                </div>
              </div>

              {selectedTreatment.recommendations.length > 0 && (
                <div>
                  <h3 className="font-bold text-dark-gray mb-3">Treatment Plan</h3>
                  <div className="space-y-3">
                    {selectedTreatment.recommendations.map((rec, i) => (
                      <div key={i} className="flex items-start gap-3 p-3 bg-blue-50 rounded-xl border border-blue-100">
                        <RecIcon type={rec.type} />
                        <div>
                          <p className="font-semibold text-dark-gray">{rec.type}</p>
                          <p className="text-sm text-gray-600">{rec.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {selectedTreatment.notes && (
                <div>
                  <h3 className="font-bold text-dark-gray mb-3">Clinical Notes</h3>
                  <p className="text-sm text-gray-600 p-4 bg-blue-50 rounded-xl border border-blue-100">
                    {selectedTreatment.notes}
                  </p>
                </div>
              )}

              {selectedTreatment.warnings?.length > 0 && (
                <div>
                  <h3 className="font-bold text-dark-gray mb-3">⚠️ Warnings</h3>
                  <div className="space-y-2">
                    {selectedTreatment.warnings.map((w, i) => (
                      <div key={i} className="flex gap-2 p-3 bg-red-50 border border-red-100 rounded-xl">
                        <AlertCircle className="w-4 h-4 text-danger flex-shrink-0 mt-0.5" />
                        <p className="text-sm text-red-700">{w}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            <div className="flex gap-3 p-6 border-t border-border-gray">
              <button
                onClick={() => handlePrint(selectedTreatment)}
                className="btn-secondary flex items-center gap-2 flex-1"
              >
                <Printer className="w-4 h-4" />
                Print Plan
              </button>
              <button
                onClick={() => setSelectedTreatment(null)}
                className="btn-primary flex-1"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <Footer />
    </div>
  );
}

export default TreatmentRecommendations;
